import type { Metadata } from 'next'
import { Providers } from './providers'
import "./globals.css"
import { Nav } from '@/components/nav'
import { Heading } from '@chakra-ui/react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Nav/>

          {children}
        </Providers>
      </body>
    </html>
  )
}
